### ISSUE TITLE
Choose a language to use to create dpcl

### ISSUE THREAD

**Issue by ElFeesho** [AlexAhern/dpcl#3]
A language should be chosen that best matches expected uses of dpcl.

Should investigate:
- [x] Tooling
- [x] Testing frameworks
- [x] Networking
- [x] JSON processing
- [x] Console output capabilities

**Comment by Yosaron** [comment]
Chose Ruby for the project, using a BDD cycle.
The testing frameworks will be rspec for the unit tests and cucumber for the BDD tests.
For networking net/http from the standard library should suffice, and JSON processing is supported nicely by the json gem.
The code will be written in vim it is perfect for the command line, but would not rule out an alternative if there was some benefit.
